### ISSUE TITLE
Flavors: How to preserve specific optionality in pkgsrc builds?

### ISSUE THREAD

**Issue by Kerrnel** [NetBSDfr/pkgin#135]
Gentoo has flags to set the flavour of a platform. Obviously pkgsrc has make options.

My current problem: cyrus-saslauthd - I need ldap enabled - but pkgin repo has it disabled.

How is this situation to be managed with pkgin? Can my own source install be "locked" or trigger a source build? Could the repository carry options-set (from make show-options) variations that could be configured?

Doesn't seem obvious but I could obviously be missing something. I suppose cyrus-saslauthd-ldap could be its own pkgsrc/wip entry.

**Comment by jperkin** [comment]
Which repository is this? Both the macOS and illumos package sets enable the `ldap` option by default.

**Comment by Kerrnel** [comment]
NetBSD (10rc6)

**Comment by jperkin** [comment]
Ok, and are these packages from pkgsrc.smartos.org or from NetBSD?

**Comment by Kerrnel** [comment]
https://cdn.netbsd.org/pub/pkgsrc/packages/NetBSD/$arch/10.0/All

**Comment by jperkin** [comment]
Ok, yeh, the NetBSD builds are always done with default options, and there's no point asking them to change that. The packages I provide from pkgsrc.smartos.org including the NetBSD ones have lots of options enabled including `ldap` (because I believe they are more useful to more people that way).

If it's possible to provide separate modules as different packages then yes that's the best way to do this, we do that where possible.

In terms of how pkgin handles this, everything is keyed on PKGPATH, so if you want to provide your own build of this package then it needs to be done in a different source path, for example `local/cyrus-saslauthd`, and then pkgin will consider yours only and not try to overwrite it with `security/cyrus-saslauthd` from the main repository.

Hope that helps.

**Comment by Kerrnel** [comment]
Thanks for your (very quick) help - changed to https://pkgsrc.smartos.org/packages/NetBSD/trunk/x86_64/All in /usr/pkg/etc/repositiories.conf and after upgrade - ldap is indeed enabled.

(I wasn't trying to be a snob with just the NetBSD.org repot - if I had read more, I'd have stumbled upon using smartos. Thanks for your contributions! Been using src via pkgsrc for 25 years - I guess prebuilts time has arrived ;) ... Perhaps if anything a choice on first run from a list of repot / benefits would be a nifty addition.)
